### ISSUE TITLE
Reading Boolean inside an FB which is instantiated in an Array

### ISSUE THREAD

**Issue by seehma** [MrLeeh/pyads#15]
Hi,

First, thanks for this python library. It makes it very easy to access PLC variables.
I have one problem accessing a Boolean inside an FB which is instantiated in an Array.
I have the following scenario:

- I have an FB calls IoOutput with a output_ AT%Q* : BOOL instantiated inside
- This IoOutput FB is instantiated as an Array of three outputs (output_[0], output_[1], output_[2])
- And this Array is instantiated in another FB and so on to finally hosted in the MAIN Prg

Now i want to access the Boolean inside the IoOutput FB but that does not work
I tried the following call: redLight = pyads.read_by_name(adr, 'MAIN.ampel1_.output_.output_[0].output_', pyads.PLCTYPE_BOOL)

Did you try such an example => Accessing Variables in FBs which are instantiated as Array?

Hope you understand my problem, maybe with the pic attached...

Thanks,

Matthias
![output](https://cloud.githubusercontent.com/assets/7335330/19048945/ad3a16ec-89a8-11e6-8192-49a9afeb66ac.PNG)
![symbolnotfound](https://cloud.githubusercontent.com/assets/7335330/19049040/07313e3c-89a9-11e6-835a-0381c434c978.PNG)

Edit1: I know that the error (ADSError: Symbol not found) comes up with this call, but i can normally access another variable which is not instantiated inside an array of FB
Edit2: My first try was without the trailing slash, my second try was with trailing slash which you can see inside the command window

**Comment by seehma** [comment]
OMG.

Beginners Mistake => The error Message was correct, i had one output_ too much in my Handle Name.

Sorry for that Issue, you can close it!

**Comment by MrLeeh** [comment]
Alright. Glad that things worked out :)
