### ISSUE TITLE
Method existance check in "adsSyncReadWriteReq"

### ISSUE THREAD

**Issue by Digides** [MrLeeh/pyads#7]
When i was trying to rewrite the "Reading the PLC variable declaration of an individual variable" example  from "https://infosys.beckhoff.com/content/1033/tc3_adssamples_c/html/tcadsdll_api_cpp_sample14.htm?id=17573" in Python i got the following error.

C:\test>python pyads_dump_single.py
Traceback (most recent call last):
  File "pyads_dump_single.py", line 26, in <module>
    dataSIBN = adsSyncReadWriteReq(adr, ADSIGRP_SYM_INFOBYNAMEEX, 0, bufferType,
 varName, PLCTYPE_STRING)
  File "C:\Python27\lib\site-packages\pyads\pyads.py", line 260, in adsSyncReadW
riteReq
    return readData.value
AttributeError: 'c_ubyte_Array_65535' object has no attribute 'value'

 So i decided to add method existance check to the adsSyncReadWriteReq function on my PC, just like it is done in the "adsSyncReadReq" 

    # ORIGINAL
    #return readData.value
    # ORIGINAL
    
    # TEST
    if hasattr(readData, 'value'):
        return readData.value
    else:
        if type(plcReadDataType).__name__ == 'PyCArrayType':
            dout = [i for i in readData]
            return dout
        else:
            # if we return structures, they may not have a value attribute
            return readData
    # TEST

and after that it works fine. May be it should be done in the "pyads" library somehow.

**Comment by MrLeeh** [comment]
Thanks for reporting this. I added your suggestions.
