### ISSUE TITLE
Missed field in the "SAdsSymbolEntry" sructure

### ISSUE THREAD

**Issue by Digides** [MrLeeh/pyads#8]
When i was trying to read the variables information from the runtime like in the "Read PLC variable declaration" example from "https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_adssamples_c/html/tcadsdll_api_cpp_sample10.htm&id=17583" in Python i have found that the "dataType" field was missed the "SAdsSymbolEntry" sructure. The next important thing is that ctypes strucures without "_pack_ = 1" field can have wrong size in bytes and field values in such structure may be wrong after the data were copied in that structure.
Here is the test script http://pastebin.com/qGMnkK2F
And its output on my PC http://pastebin.com/Q1hNFZQj

**Comment by MrLeeh** [comment]
Thanks for reporting this. The missing field was a writing mistake of mine. Concerning the _pack_=1 thing I didn' t recognize the #pragma in the c header. Fixed this for the other structures as well.
