### ISSUE TITLE
adsSyncWriteByName and STRING

### ISSUE THREAD

**Issue by pjaneck** [MrLeeh/pyads#9]
Hi,
maybe I'm doing something wrong, but I can't read and write STRING variables from TwinCAT (2.11) using the adsSyncWriteByName methode. When reading it returns just the first character and when writing it throws: "ADSError: parameter size not correct (1797)".

Thanks for any help,
Peter

PS: I looked up the implementation of PLCTYPE_STRING and found that it is just a c_char. So the solution is to multiply the type by the length of the string... Too simple...
Thanks for the nice wrapper!

**Comment by MrLeeh** [comment]
Hey Peter,
thanks for the Feedback. 
Greetings
